### ISSUE TITLE
droptopfour.com is not working

### ISSUE THREAD

**Issue by WilliamRandol** [Droptop-Four/Basic-Version#55]
**Describe the bug**
It looks like http(s)://droptopfour.com is automatically redirecting to https://www.dropboxfour.com. But it looks like the DNS is not properly resolving for the www subdomain.

**To Reproduce**
1. Go to 'http://droptopfour.com'
4. See error (in chrome) "This site can’t be reached www.droptopfour.com’s server IP address could not be found."

**Expected behavior**
See the droptopfour.com website.

**Screenshots**

![image](https://user-images.githubusercontent.com/2567079/224183300-8457c586-8549-437b-8eda-f36992420eac.png)
![image](https://user-images.githubusercontent.com/2567079/224183371-a75b6aa7-2d6f-4d07-8339-fac43f659176.png)
![image](https://user-images.githubusercontent.com/2567079/224183399-954ea9e1-cc86-4a30-8bec-f1112860fd2a.png)

**Additional context**

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

**Comment by 66Bunz** [comment]
@WilliamRandol no idea why it does that sometimes, but after some time it should fix itself

**Comment by M4dGun** [comment]
It's still offline..

**Comment by 66Bunz** [comment]
@M4dGun are you using firefox?

**Comment by WilliamRandol** [comment]
It is still broken for me in Chrome, I have to have this in my hosts file to let me use the site...

`185.199.111.153 www.droptopfour.com`

**Comment by 66Bunz** [comment]
@WilliamRandol from what country are you from? It looks like a dns problem, not sure how to solve it

**Comment by 66Bunz** [comment]
@M4dGun in firefox go to the network settings, enable  `enable DNS over HTTPS`

**Comment by WilliamRandol** [comment]
I'm in the US, using Cloudfare DNS over https as my primary, and using Google DNS over https as my secondary.

Using external tools like dnschecker.org, also show problems around the world resolving www.droptopfour.com.

I am totally willing to help identify the issue if you want.

**Comment by 66Bunz** [comment]
Any help is appreciated.
We are using google domains as a registrar and dns. I followed the instructions on the github pages wiki, I don't think I made any mistake...

**Comment by WilliamRandol** [comment]
What is set up in the DNS for the www? Is it set as an A record or a cname?

I've joined the Discord to help with communication.

**Comment by 66Bunz** [comment]
www is set as a cname that goes to `https://droptop-four.github.io.`

**Comment by WilliamRandol** [comment]
hmm.. okay, well it seems to be working now... I was able to remove the entry from my hosts file. And that is the way they say to set it up...  I don't know why it wasn't working for me for like a month... Glad to see it working now.

**Comment by 66Bunz** [comment]
Solved by removing the leading `https://` in front of `https://droptop-four.github.io`
